name: "Generate EIHL Calendar's"
on:
  workflow_dispatch:
    
  schedule:
    - cron: 45 23 * * 0
jobs:
  calendar-generation:
    runs-on: Windows-Latest
    steps:
      - name: Set GB Culture
        shell: pwsh
        run: Set-Culture en-GB
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install Powershell
        run: dotnet tool install -g PowerShell
      - name: Install Playwright
        working-directory: src/EliteLeagueScheduleIcsGenerator
        run: pwsh ./bin/Debug/net9.0/playwright.ps1 install --with-deps
      - name: Run Calendar Generation
        working-directory: src/EliteLeagueScheduleIcsGenerator
        run: dotnet run
        env: 
          TZ: "Europe/London"
      - uses: EndBug/add-and-commit@v9
        with:
          add: Output
          message: "Update EIHL ICS with latest fixtures"
          committer_name: GitHub Actions
          committer_email: actions@github.com
