name: "Generate EIHL Calendar's"
on:
  workflow_dispatch:
    
  schedule:
    - cron: 45 23 * * 0
jobs:
  calendar-generation:
    runs-on: Windows-Latest
    steps:
      - name: Set GB Culture
        shell: pwsh
        run: Set-Culture en-GB
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install Playwright
        working-directory: src/EliteLeagueScheduleIcsGenerator
        run: bin/Debug/net9.0/playwright.ps1 install
      - name: Run Calendar Generation
        working-directory: src/EliteLeagueScheduleIcsGenerator
        run: dotnet run
        env: 
          TZ: "Europe/London"
      - uses: EndBug/add-and-commit@v9
        with:
          add: Output
          message: "Update EIHL ICS with latest fixtures"
          new_branch: updates/LatestFixturesIcs
      - name: create pull request
        run: gh pr create -B main -H updates/LatestFixturesIcs --title 'Update ICS Test' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
